apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /etc/mysql/conf.d
            name: mysql-config

        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-sc
              key: rootpassword

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-sc
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-sc
              key: user
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-sc
              key: db
       
      volumes:
        - name: mysql-config
          persistentVolumeClaim:
            claimName: pvc-mysql
