kind: Service
apiVersion: v1
metadata:
  name: wordpress-nodeport
  namespace: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  
